domain_path: C:\Aakarsh_Files\Implementation-on-Zedboard\Zynq7_series\platform_exp\export\platform_exp\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
